package com.example.projemanager.utils

object Constants {
    const val USERS: String = "users"
    const val IMAGE: String = "image"
    const val MOBILE: String = "mobile"
    const val NAME: String = "name"
    const val ID: String = "id"
    const val BOARDS: String = "boards"
    const val ASSIGNED_TO : String = "assignedTo"
    const val DOCUMENT_ID: String = "documentId"
    const val TASK_LIST: String = "taskList"
    const val EMAIL: String = "email"
    const val TASK_LIST_ITEM_POSITION: String = "task_list_item_position"
    const val CARD_LIST_ITEM_POSITION: String = "card_list_item_position"
    const val BOARD_MEMBERS_LIST: String = "board_members_list"
    const val SELECT: String = "Select"
    const val UN_SELECT: String = "UnSelect"
    const val PROJEMANAGER_PREFERENCES: String = "ProjeManagePrefs"
    const val FCM_TOKEN_UPDATED: String = "fcmTokenUpdated"
    const val FCM_TOKEN: String = "fcmToken"
    const val FCM_BASE_URL: String = "https://fcm.googleapis.com/fcm/send"
    const val FCM_AUTHORISATION: String = "authorisation"
    const val FCM_KEY: String = "key"
    const val FCM_SERVER_KEY: String = "AAAANYoxhak:APA91bEZ3GSoy7ezf_prATcJ126_zKeU_yLGNBSn8ETfxnMsJuKcFF5MTDX1yyV70xK8Dw_PsY-gjCEIFsDw4_qg6Xghh5jo3WyeWrNDGhjxWwN8k2VeSWlHCnRW54wUBhvsTXZTh-Wi"
    const val FCM_KEY_TITLE: String = "title"
    const val FCM_KEY_MESSAGE: String = "message"
    const val FCM_KEY_DATA: String = "data"
    const val FCM_KEY_TO: String = "to"
}